Scripts/simple/simple/core/urls.py
# """simple URL Configuration.
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/2.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
from django.urls import path
from simple.core.views import hello, contact

# The app_name is necessary if you wanna to declare a namespace to your routes
app_name = 'core'

urlpatterns = [
    path('', hello, name='hello'),
    path('hello/', hello, name='hello'),
    path('contact/', contact, name='contact'),
]

Scripts/simple/simple/courses/urls.py
# """simple URL Configuration.
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/2.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
from django.urls import path
from simple.courses.views import index, details

# The app_name is necessary if you wanna to declare a namespace to your routes
app_name = 'courses'

urlpatterns = [
    path('', index, name='index'),
    path('index/', index, name='index'),
    path('<int:id>/', details, name='details'),
]

Scripts/simple/simple/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('simple.core.urls', namespace='core')),
    path('courses/', include('simple.courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Scripts/simple/simple/core/models.py
from django.db import models

# Create your models here.

Scripts/simple/simple/courses/models.py
from django.db import models


class CourseManager(models.Manager):
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) |
            models.Q(description__icontains=query) |
            models.Q(slug__icontains=query)
        )


class Courses(models.Model):
    name = models.CharField(
        'Nome',
        max_length=100
    )
    slug = models.SlugField(
        'Atalho'
    )
    description = models.TextField(
        'Descrição',
        blank=True
    )
    about = models.TextField(
        'Sobre',
        blank=True
    )
    image = models.ImageField(
        upload_to='courses/images',
        verbose_name='Imagen',
        null=True,
        blank=True
    )
    start_date = models.DateField(
        'Data início',
        null=True,
        blank=True
    )
    created_at = models.DateField(
        'Criado em ',
        auto_now_add=True
    )
    updated_at = models.DateField(
        'Atualizado em ',
        auto_now=True
    )
    objects = CourseManager()

    def __str__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('courses:details', (), {'id': self.id})

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']

Scripts/simple/simple/core/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        label='Nome',
        max_length=100
    )
    email = forms.CharField(
        label='Email'
    )
    message = forms.CharField(
        label='Mensagem',
        widget=forms.Textarea
    )

Scripts/simple/simple/core/views.py
from django.shortcuts import render
from django.http import HttpResponse  # Add isso

from .forms import ContactForm


def hello(request):
    return render(request, 'home.html')


def contact(request):
    context = {}
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            print(form.cleaned_data)
            form = ContactForm()
    else:
        form = ContactForm()
        context['form'] = form
        context['is_valid'] = False
    return render(request, 'contact.html', context)

Scripts/simple/simple/courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse  # Add isso

from .models import Courses


def index(request):
    courses = Courses.objects.all()
    template_name = 'courses/index.html'
    context = {
        'courses': courses
    }
    return render(request, template_name, context)


def details(request, id):
    # course =  Courses.objects.get(id=id)
    course = get_object_or_404(Courses, id=id)
    template_name = 'courses/details.html'
    context = {
        'course': course,
    }
    return render(request, template_name, context)

Scripts/simple/simple/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/sticky-footer.css' %}" />
  <body cz-shortcut-listen="true">

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'core:hello' %}">Simple</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'core:hello' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'courses:index' %}">Cursos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:contact' %}">Contato</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="mt-3">
        {% block content %} {% endblock %}
      </div>
    </main>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">Rodape</span>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  </body>
</html>

Scripts/simple/simple/core/templates/contact.html
{% extends 'base.html' %}

{% block content %}

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Fale Conosco</h1>
      </div>
    </div>
    <hr>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-12">

          {% if is_valid %}
          <p>Sua mensagem foi enviada.</p>
          <div class="form-group row">
            <div class="col-sm-10">
              <a class="btn btn-primary" href="{% url 'core:contact' %}">
                Enviar nova mensagem
              </a>
            </div>
          </div>
          {% else %}
          <form action="{% url 'core:contact' %}" method="post">
            {% csrf_token %}
            <!-- {{ form.as_p }} -->

            {% for field in form %}
            <div class="form-group row">
              <label for="inputPassword3" class="col-sm-2 col-form-label">{{ field.label }}</label>
              <div class="col-sm-10">
                  {{ field }}
                  {{ field.errors }}
              </div>
            </div>
            {% endfor %}

            <div class="form-group row">
              <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>

          </form>
          {% endif %}

        </div>
      </div>
    </div> <!-- /container -->

{% endblock %}

Scripts/simple/simple/core/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Hello, world!</h1>
{% endblock %}

Scripts/simple/simple/courses/templates/courses/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">{{ course }}</h1>
          <p style="margin-bottom:50px">{{ course.description }}</p>

          <p><a class="btn btn-primary btn-lg" href="#" role="button">Ir para o curso »</a></p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-12">
            {% if course.about %}
            <p class="text-justify">
              {{ course.about|linebreaks }}
            </p>
            {% else %}
            <p class="text-justify">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed arcu sem, egestas in ante quis, cursus gravida magna. Maecenas pharetra urna et luctus laoreet. Duis ut fermentum libero, vehicula luctus augue. Integer malesuada turpis eu risus gravida, ut iaculis risus ultrices. Praesent at elit felis. Morbi bibendum dignissim sem, vel semper massa pellentesque non. Duis mollis justo non cursus auctor. Fusce vitae tortor sodales, finibus dolor vitae, sodales nunc. Fusce ac commodo libero. Ut ut pulvinar odio.
            </p>
            <p class="text-justify">
              Cras sed quam quis eros hendrerit rutrum. Vivamus id pretium sapien. Donec fermentum scelerisque lorem, vitae rhoncus nulla rutrum et. Donec neque turpis, maximus et tincidunt eget, lacinia non nulla. Aliquam mauris magna, dignissim a sagittis molestie, dictum id felis. Vivamus in diam vestibulum, faucibus libero quis, tristique lectus. Morbi mollis sem neque, sed vulputate nunc elementum in. In tempor malesuada laoreet. In in imperdiet augue. Donec lobortis posuere arcu, quis sollicitudin nunc cursus in. Praesent tristique eleifend commodo. In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
            </p>
            <p class="text-justify">
              Fusce vestibulum ex ligula, at auctor dui sagittis vel. Ut justo lacus, commodo sit amet dui in, rhoncus tempor lacus. Vestibulum molestie massa vitae elit finibus, a ultrices leo consequat. Ut ullamcorper sollicitudin lorem, eget tincidunt nunc lacinia sit amet. Nullam sit amet purus hendrerit, viverra lectus eget, volutpat erat. Maecenas nec turpis finibus, posuere magna eget, dictum mauris. Morbi at magna lacus. Aliquam dignissim velit et nibh elementum, quis lobortis ex pulvinar. Aenean consequat quam a euismod pharetra. Praesent viverra lectus placerat fermentum suscipit. Aliquam efficitur ante et lacus posuere, ut sollicitudin metus porttitor. Maecenas sed varius mi. Cras ullamcorper gravida lorem, at commodo enim molestie non.
            </p>
            <p class="text-justify">
              Curabitur eget felis malesuada tellus accumsan faucibus. Nullam vitae nisi et dui dignissim rutrum. Nullam a semper metus, vitae rutrum tortor. Quisque eleifend malesuada blandit. Integer iaculis risus ac mauris interdum dictum. Nam vel mattis urna. Maecenas volutpat massa quis magna finibus, eget porta tellus mollis. Fusce eget mattis mauris. Vivamus eget quam id nibh rutrum vehicula eget eu neque. Nullam tincidunt urna ut urna scelerisque consectetur. Fusce et tellus ligula. Sed et lorem imperdiet, efficitur elit non, pulvinar nulla. Sed elementum sit amet orci in pretium. In sit amet accumsan sem.
            </p>
            <p class="text-justify">
              Aliquam non sapien sed quam rutrum dictum non a ante. Curabitur ac tellus arcu. Suspendisse feugiat non velit interdum hendrerit. Suspendisse fermentum quis ante quis porta. Quisque fermentum, nisi id placerat posuere, sem dolor sodales ipsum, ac scelerisque est est quis diam. Mauris in mi arcu. Fusce semper urna tincidunt, rhoncus dui in, mollis nisi. Nulla facilisi. Integer quis pellentesque urna. Vivamus condimentum sollicitudin eros, a pretium lectus dapibus bibendum.
            </p>
            {% endif %}
          </div>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>
{% endblock %}

Scripts/simple/simple/courses/templates/courses/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Lista de Cursos</h1>
  {% for course in courses %}
  <a href="{{ course.get_absolute_url }}">
    <div class="alert alert-info" role="alert">
      <div class="row">
        {% if course.image %}
        <img class="col-md-3" src="{{ course.image.url }}" alt="{{ course }}">
        {% else  %}
        <img class="col-md-3" src="{% static 'img/curso.png' %}" alt="{{ course }}">
        {% endif %}
        <div class="col-md-9">
          <h4 class="alert-heading">{{ course }}</h4>
          <p>{{ course.description|linebreaks }}</p>
          <hr>
          <p class="mb-0">resumo</p>
        </div>
      </div>
    </div>
  </a>
  {% empty  %}
  <div class="alert alert-success" role="alert">
    <div class="row">
      <div class="col-md-9">
        <h4 class="alert-heading">Oopss!</h4>
        <p>Nao ha cursos disponiveis</p>
      </div>
    </div>
  </div>
  {% endfor %}
{% endblock %}